name: personal_finance_app
description: A personal finance management app.

# The version. It follows the semantic versioning format.
version: 1.0.0+1

# The environment section specifies the Flutter SDK version constraints.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.3
  sqflite: ^2.2.5+1
  path_provider: ^2.1.2
  charts_flutter_new: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# Additional Flutter-specific settings.
flutter:
  uses-material-design: true

  # The assets section lists all the files and directories that should be included
  assets:
    - assets/images/
    - assets/fonts/

  # Custom fonts.
  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/fonts/CustomFont-Regular.ttf
        - asset: assets/fonts/CustomFont-Bold.ttf
          weight: 700
